[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/deploily-addons,/mnt/oca-addons

wkhtmltopdf = /usr/local/bin/wkhtmltopdf_utf8.sh

db_host = db
db_user = odoo
db_password = odoo
